puts "+-------------------------------------------+";
puts "Creating Functional Synth";
puts "# of Args $argc";

set dcp_file [lindex $argv 0];
puts [format "DCP: %s" $dcp_file];

set dirname [file dirname $dcp_file];
puts [format "Dir: %s" $dirname];

set rootname [file rootname [file tail $dcp_file]];
set comp [split $rootname "_"];
set comp [lreplace $comp 0 0];
set joined [join $comp "_"];
set synth_file [format "%s/sim/synth/func/autogenerated_tb_synth_func.v" $dirname];
#set synth_file [format "%s/sim/synth/func/NiFpgaIPWrapper_%s_synth_func.vhd" $dirname $joined];
puts [format "Synth File: %s" $synth_file];

open_checkpoint $dcp_file;
write_verilog -mode funcsim -nolib -force -file $synth_file;

puts "Done";
puts "+-------------------------------------------+";
