-- VHDL wrapper for NiFpgaAG_poc_ip
-- Generated by LabVIEW FPGA IP Export Utility
--
-- Ports:
-- reset      :  Reset port. Minimum assertion length: 8 base clock cycles.
--               Minimum de-assertion length: 100 base clock cycles.
-- enable_in  :  Enable in port. Minimum re-initialization length: 7 base clock cycles.
-- enable_out :  Enable out port.
-- enable_clr :  Enable clear port.
-- ctrlind_00_CMD_TVALID : Top level indicator "CMD.TVALID", sync to Clk40Derived5x2B00MHz, bool
-- ctrlind_01_CMD_TLAST : Top level indicator "CMD.TLAST", sync to Clk40Derived5x2B00MHz, bool
-- ctrlind_02_CMD_TKEEP : Top level indicator "CMD.TKEEP", sync to Clk40Derived5x2B00MHz, u8
-- ctrlind_03_CMD_TDATA : Top level indicator "CMD.TDATA", sync to Clk40Derived5x2B00MHz, u64
-- ctrlind_04_DEBUG_TVALID : Top level indicator "DEBUG.TVALID", sync to Clk40Derived5x2B00MHz, bool
-- ctrlind_05_DEBUG_TLAST : Top level indicator "DEBUG.TLAST", sync to Clk40Derived5x2B00MHz, bool
-- ctrlind_06_DEBUG_TKEEP : Top level indicator "DEBUG.TKEEP", sync to Clk40Derived5x2B00MHz, u8
-- ctrlind_07_DEBUG_TDATA : Top level indicator "DEBUG.TDATA", sync to Clk40Derived5x2B00MHz, u64
-- ctrlind_08_TUSER : Top level control "TUSER", sync to Clk40Derived5x2B00MHz, bool
-- ctrlind_09_TLAST : Top level control "TLAST", sync to Clk40Derived5x2B00MHz, bool
-- ctrlind_10_TVALID : Top level control "TVALID", sync to Clk40Derived5x2B00MHz, bool
-- ctrlind_11_TKEEP : Top level control "TKEEP", sync to Clk40Derived5x2B00MHz, u8
-- ctrlind_12_TDATA : Top level control "TDATA", sync to Clk40Derived5x2B00MHz, u64
-- ctrlind_13_ip_reset : Top level control "ip.reset", sync to Clk40Derived5x2B00MHz, bool
-- Clk40Derived5x2B00MHz : Clock "100MHz", nominal frequency 100.00 MHz, base clock

library ieee;
use ieee.std_logic_1164.all;

entity NiFpgaIPWrapper_poc_ip is
		port (
			reset : in std_logic;
			enable_in : in std_logic;
			enable_out : out std_logic;
			enable_clr : in std_logic;
			ctrlind_00_CMD_TVALID : out std_logic_vector(0 downto 0);
			ctrlind_01_CMD_TLAST : out std_logic_vector(0 downto 0);
			ctrlind_02_CMD_TKEEP : out std_logic_vector(7 downto 0);
			ctrlind_03_CMD_TDATA : out std_logic_vector(63 downto 0);
			ctrlind_04_DEBUG_TVALID : out std_logic_vector(0 downto 0);
			ctrlind_05_DEBUG_TLAST : out std_logic_vector(0 downto 0);
			ctrlind_06_DEBUG_TKEEP : out std_logic_vector(7 downto 0);
			ctrlind_07_DEBUG_TDATA : out std_logic_vector(63 downto 0);
			ctrlind_08_TUSER : in std_logic_vector(0 downto 0);
			ctrlind_09_TLAST : in std_logic_vector(0 downto 0);
			ctrlind_10_TVALID : in std_logic_vector(0 downto 0);
			ctrlind_11_TKEEP : in std_logic_vector(7 downto 0);
			ctrlind_12_TDATA : in std_logic_vector(63 downto 0);
			ctrlind_13_ip_reset : in std_logic_vector(0 downto 0);
			Clk40Derived5x2B00MHz : in std_logic
		);
end NiFpgaIPWrapper_poc_ip;

architecture vhdl_labview of NiFpgaIPWrapper_poc_ip is

	component NiFpgaAG_poc_ip
		port (
			reset : in std_logic;
			enable_in : in std_logic;
			enable_out : out std_logic;
			enable_clr : in std_logic;
			ctrlind_00_CMD_TVALID : out std_logic_vector(0 downto 0);
			ctrlind_01_CMD_TLAST : out std_logic_vector(0 downto 0);
			ctrlind_02_CMD_TKEEP : out std_logic_vector(7 downto 0);
			ctrlind_03_CMD_TDATA : out std_logic_vector(63 downto 0);
			ctrlind_04_DEBUG_TVALID : out std_logic_vector(0 downto 0);
			ctrlind_05_DEBUG_TLAST : out std_logic_vector(0 downto 0);
			ctrlind_06_DEBUG_TKEEP : out std_logic_vector(7 downto 0);
			ctrlind_07_DEBUG_TDATA : out std_logic_vector(63 downto 0);
			ctrlind_08_TUSER : in std_logic_vector(0 downto 0);
			ctrlind_09_TLAST : in std_logic_vector(0 downto 0);
			ctrlind_10_TVALID : in std_logic_vector(0 downto 0);
			ctrlind_11_TKEEP : in std_logic_vector(7 downto 0);
			ctrlind_12_TDATA : in std_logic_vector(63 downto 0);
			ctrlind_13_ip_reset : in std_logic_vector(0 downto 0);
			Clk40Derived5x2B00MHz : in std_logic;
			tDiagramEnableOut : in std_logic
		);
	end component;

begin
	MyLabVIEWIP : NiFpgaAG_poc_ip
		port map(
			reset => reset,
			enable_in => enable_in,
			enable_out => enable_out,
			enable_clr => enable_clr,
			ctrlind_00_CMD_TVALID => ctrlind_00_CMD_TVALID,
			ctrlind_01_CMD_TLAST => ctrlind_01_CMD_TLAST,
			ctrlind_02_CMD_TKEEP => ctrlind_02_CMD_TKEEP,
			ctrlind_03_CMD_TDATA => ctrlind_03_CMD_TDATA,
			ctrlind_04_DEBUG_TVALID => ctrlind_04_DEBUG_TVALID,
			ctrlind_05_DEBUG_TLAST => ctrlind_05_DEBUG_TLAST,
			ctrlind_06_DEBUG_TKEEP => ctrlind_06_DEBUG_TKEEP,
			ctrlind_07_DEBUG_TDATA => ctrlind_07_DEBUG_TDATA,
			ctrlind_08_TUSER => ctrlind_08_TUSER,
			ctrlind_09_TLAST => ctrlind_09_TLAST,
			ctrlind_10_TVALID => ctrlind_10_TVALID,
			ctrlind_11_TKEEP => ctrlind_11_TKEEP,
			ctrlind_12_TDATA => ctrlind_12_TDATA,
			ctrlind_13_ip_reset => ctrlind_13_ip_reset,
			Clk40Derived5x2B00MHz => Clk40Derived5x2B00MHz,
			tDiagramEnableOut => '1'
		);

end vhdl_labview;

