-- VHDL wrapper for NiFpgaAG_fpga_sandbox_ip
-- Generated by LabVIEW FPGA IP Export Utility
--
-- Ports:
-- reset      :  Reset port. Minimum assertion length: 8 base clock cycles.
--               Minimum de-assertion length: 40 base clock cycles.
-- enable_in  :  Enable in port. Minimum re-initialization length: 7 base clock cycles.
-- enable_out :  Enable out port.
-- enable_clr :  Enable clear port.
-- ctrlind_00_DEBUG_TVALID : Top level indicator "DEBUG.TVALID", sync to Clk40, bool
-- ctrlind_01_DEBUG_TLAST : Top level indicator "DEBUG.TLAST", sync to Clk40, bool
-- ctrlind_02_DEBUG_TKEEP : Top level indicator "DEBUG.TKEEP", sync to Clk40, u8
-- ctrlind_03_DEBUG_TDATA : Top level indicator "DEBUG.TDATA", sync to Clk40, u64
-- ctrlind_04_TUSER : Top level control "TUSER", sync to Clk40, bool
-- ctrlind_05_TLAST : Top level control "TLAST", sync to Clk40, bool
-- ctrlind_06_TVALID : Top level control "TVALID", sync to Clk40, bool
-- ctrlind_07_TKEEP : Top level control "TKEEP", sync to Clk40, u8
-- ctrlind_08_TDATA : Top level control "TDATA", sync to Clk40, u64
-- ctrlind_09_ip_reset : Top level control "ip.reset", sync to Clk40, bool
-- Clk40 : Clock "40 MHz Onboard Clock", nominal frequency 40.00 MHz, base clock

library ieee;
use ieee.std_logic_1164.all;

entity NiFpgaIPWrapper_fpga_sandbox_ip is
		port (
			reset : in std_logic;
			enable_in : in std_logic;
			enable_out : out std_logic;
			enable_clr : in std_logic;
			ctrlind_00_DEBUG_TVALID : out std_logic_vector(0 downto 0);
			ctrlind_01_DEBUG_TLAST : out std_logic_vector(0 downto 0);
			ctrlind_02_DEBUG_TKEEP : out std_logic_vector(7 downto 0);
			ctrlind_03_DEBUG_TDATA : out std_logic_vector(63 downto 0);
			ctrlind_04_TUSER : in std_logic_vector(0 downto 0);
			ctrlind_05_TLAST : in std_logic_vector(0 downto 0);
			ctrlind_06_TVALID : in std_logic_vector(0 downto 0);
			ctrlind_07_TKEEP : in std_logic_vector(7 downto 0);
			ctrlind_08_TDATA : in std_logic_vector(63 downto 0);
			ctrlind_09_ip_reset : in std_logic_vector(0 downto 0);
			Clk40 : in std_logic
		);
end NiFpgaIPWrapper_fpga_sandbox_ip;

architecture vhdl_labview of NiFpgaIPWrapper_fpga_sandbox_ip is

	component NiFpgaAG_fpga_sandbox_ip
		port (
			reset : in std_logic;
			enable_in : in std_logic;
			enable_out : out std_logic;
			enable_clr : in std_logic;
			ctrlind_00_DEBUG_TVALID : out std_logic_vector(0 downto 0);
			ctrlind_01_DEBUG_TLAST : out std_logic_vector(0 downto 0);
			ctrlind_02_DEBUG_TKEEP : out std_logic_vector(7 downto 0);
			ctrlind_03_DEBUG_TDATA : out std_logic_vector(63 downto 0);
			ctrlind_04_TUSER : in std_logic_vector(0 downto 0);
			ctrlind_05_TLAST : in std_logic_vector(0 downto 0);
			ctrlind_06_TVALID : in std_logic_vector(0 downto 0);
			ctrlind_07_TKEEP : in std_logic_vector(7 downto 0);
			ctrlind_08_TDATA : in std_logic_vector(63 downto 0);
			ctrlind_09_ip_reset : in std_logic_vector(0 downto 0);
			Clk40 : in std_logic;
			tDiagramEnableOut : in std_logic
		);
	end component;

begin
	MyLabVIEWIP : NiFpgaAG_fpga_sandbox_ip
		port map(
			reset => reset,
			enable_in => enable_in,
			enable_out => enable_out,
			enable_clr => enable_clr,
			ctrlind_00_DEBUG_TVALID => ctrlind_00_DEBUG_TVALID,
			ctrlind_01_DEBUG_TLAST => ctrlind_01_DEBUG_TLAST,
			ctrlind_02_DEBUG_TKEEP => ctrlind_02_DEBUG_TKEEP,
			ctrlind_03_DEBUG_TDATA => ctrlind_03_DEBUG_TDATA,
			ctrlind_04_TUSER => ctrlind_04_TUSER,
			ctrlind_05_TLAST => ctrlind_05_TLAST,
			ctrlind_06_TVALID => ctrlind_06_TVALID,
			ctrlind_07_TKEEP => ctrlind_07_TKEEP,
			ctrlind_08_TDATA => ctrlind_08_TDATA,
			ctrlind_09_ip_reset => ctrlind_09_ip_reset,
			Clk40 => Clk40,
			tDiagramEnableOut => '1'
		);

end vhdl_labview;

