-- VHDL wrapper for NiFpgaAG_poc_ip_kria
-- Generated by LabVIEW FPGA IP Export Utility
--
-- Ports:
-- reset      :  Reset port. Minimum assertion length: 8 base clock cycles.
--               Minimum de-assertion length: 100 base clock cycles.
-- enable_in  :  Enable in port. Minimum re-initialization length: 7 base clock cycles.
-- enable_out :  Enable out port.
-- enable_clr :  Enable clear port.
-- ctrlind_00_DEBUG_TREADY : Top level control "DEBUG.TREADY", sync to Clk40MhzDerived5x2B00MHz, bool
-- ctrlind_01_DEBUG_TVALID : Top level indicator "DEBUG.TVALID", sync to Clk40MhzDerived5x2B00MHz, bool
-- ctrlind_02_DEBUG_TLAST : Top level indicator "DEBUG.TLAST", sync to Clk40MhzDerived5x2B00MHz, bool
-- ctrlind_03_DEBUG_TKEEP : Top level indicator "DEBUG.TKEEP", sync to Clk40MhzDerived5x2B00MHz, u8
-- ctrlind_04_DEBUG_TDATA : Top level indicator "DEBUG.TDATA", sync to Clk40MhzDerived5x2B00MHz, u64
-- ctrlind_05_CMD_TREADY : Top level control "CMD.TREADY", sync to Clk40MhzDerived5x2B00MHz, bool
-- ctrlind_06_CMD_TVALID : Top level indicator "CMD.TVALID", sync to Clk40MhzDerived5x2B00MHz, bool
-- ctrlind_07_CMD_TLAST : Top level indicator "CMD.TLAST", sync to Clk40MhzDerived5x2B00MHz, bool
-- ctrlind_08_CMD_TKEEP : Top level indicator "CMD.TKEEP", sync to Clk40MhzDerived5x2B00MHz, u8
-- ctrlind_09_CMD_TDATA : Top level indicator "CMD.TDATA", sync to Clk40MhzDerived5x2B00MHz, u64
-- ctrlind_10_MDEBUG_TREADY : Top level control "MDEBUG.TREADY", sync to Clk40MhzDerived5x2B00MHz, bool
-- ctrlind_11_MDEBUG_TVALID : Top level indicator "MDEBUG.TVALID", sync to Clk40MhzDerived5x2B00MHz, bool
-- ctrlind_12_MDEBUG_TLAST : Top level indicator "MDEBUG.TLAST", sync to Clk40MhzDerived5x2B00MHz, bool
-- ctrlind_13_MDEBUG_TKEEP : Top level indicator "MDEBUG.TKEEP", sync to Clk40MhzDerived5x2B00MHz, u8
-- ctrlind_14_MDEBUG_TDATA : Top level indicator "MDEBUG.TDATA", sync to Clk40MhzDerived5x2B00MHz, u64
-- ctrlind_15_TUSER : Top level control "TUSER", sync to Clk40MhzDerived168x43B56_28MHz, bool
-- ctrlind_16_TLAST : Top level control "TLAST", sync to Clk40MhzDerived168x43B56_28MHz, bool
-- ctrlind_17_TVALID : Top level control "TVALID", sync to Clk40MhzDerived168x43B56_28MHz, bool
-- ctrlind_18_TKEEP : Top level control "TKEEP", sync to Clk40MhzDerived168x43B56_28MHz, u8
-- ctrlind_19_TDATA : Top level control "TDATA", sync to Clk40MhzDerived168x43B56_28MHz, u64
-- ctrlind_20_ip_reset : Top level control "ip.reset", sync to Clk40MhzDerived168x43B56_28MHz, bool
-- Clk40MhzDerived5x2B00MHz : Clock "100MHz", nominal frequency 100.00 MHz, base clock
-- Clk40MhzDerived168x43B56_28MHz : Clock "156.28MHz", nominal frequency 156.28 MHz

library ieee;
use ieee.std_logic_1164.all;

entity NiFpgaIPWrapper_poc_ip_kria is
		port (
			reset : in std_logic;
			enable_in : in std_logic;
			enable_out : out std_logic;
			enable_clr : in std_logic;
			ctrlind_00_DEBUG_TREADY : in std_logic_vector(0 downto 0);
			ctrlind_01_DEBUG_TVALID : out std_logic_vector(0 downto 0);
			ctrlind_02_DEBUG_TLAST : out std_logic_vector(0 downto 0);
			ctrlind_03_DEBUG_TKEEP : out std_logic_vector(7 downto 0);
			ctrlind_04_DEBUG_TDATA : out std_logic_vector(63 downto 0);
			ctrlind_05_CMD_TREADY : in std_logic_vector(0 downto 0);
			ctrlind_06_CMD_TVALID : out std_logic_vector(0 downto 0);
			ctrlind_07_CMD_TLAST : out std_logic_vector(0 downto 0);
			ctrlind_08_CMD_TKEEP : out std_logic_vector(7 downto 0);
			ctrlind_09_CMD_TDATA : out std_logic_vector(63 downto 0);
			ctrlind_10_MDEBUG_TREADY : in std_logic_vector(0 downto 0);
			ctrlind_11_MDEBUG_TVALID : out std_logic_vector(0 downto 0);
			ctrlind_12_MDEBUG_TLAST : out std_logic_vector(0 downto 0);
			ctrlind_13_MDEBUG_TKEEP : out std_logic_vector(7 downto 0);
			ctrlind_14_MDEBUG_TDATA : out std_logic_vector(63 downto 0);
			ctrlind_15_TUSER : in std_logic_vector(0 downto 0);
			ctrlind_16_TLAST : in std_logic_vector(0 downto 0);
			ctrlind_17_TVALID : in std_logic_vector(0 downto 0);
			ctrlind_18_TKEEP : in std_logic_vector(7 downto 0);
			ctrlind_19_TDATA : in std_logic_vector(63 downto 0);
			ctrlind_20_ip_reset : in std_logic_vector(0 downto 0);
			Clk40MhzDerived5x2B00MHz : in std_logic;
			Clk40MhzDerived168x43B56_28MHz : in std_logic
		);
end NiFpgaIPWrapper_poc_ip_kria;

architecture vhdl_labview of NiFpgaIPWrapper_poc_ip_kria is

	component NiFpgaAG_poc_ip_kria
		port (
			reset : in std_logic;
			enable_in : in std_logic;
			enable_out : out std_logic;
			enable_clr : in std_logic;
			ctrlind_00_DEBUG_TREADY : in std_logic_vector(0 downto 0);
			ctrlind_01_DEBUG_TVALID : out std_logic_vector(0 downto 0);
			ctrlind_02_DEBUG_TLAST : out std_logic_vector(0 downto 0);
			ctrlind_03_DEBUG_TKEEP : out std_logic_vector(7 downto 0);
			ctrlind_04_DEBUG_TDATA : out std_logic_vector(63 downto 0);
			ctrlind_05_CMD_TREADY : in std_logic_vector(0 downto 0);
			ctrlind_06_CMD_TVALID : out std_logic_vector(0 downto 0);
			ctrlind_07_CMD_TLAST : out std_logic_vector(0 downto 0);
			ctrlind_08_CMD_TKEEP : out std_logic_vector(7 downto 0);
			ctrlind_09_CMD_TDATA : out std_logic_vector(63 downto 0);
			ctrlind_10_MDEBUG_TREADY : in std_logic_vector(0 downto 0);
			ctrlind_11_MDEBUG_TVALID : out std_logic_vector(0 downto 0);
			ctrlind_12_MDEBUG_TLAST : out std_logic_vector(0 downto 0);
			ctrlind_13_MDEBUG_TKEEP : out std_logic_vector(7 downto 0);
			ctrlind_14_MDEBUG_TDATA : out std_logic_vector(63 downto 0);
			ctrlind_15_TUSER : in std_logic_vector(0 downto 0);
			ctrlind_16_TLAST : in std_logic_vector(0 downto 0);
			ctrlind_17_TVALID : in std_logic_vector(0 downto 0);
			ctrlind_18_TKEEP : in std_logic_vector(7 downto 0);
			ctrlind_19_TDATA : in std_logic_vector(63 downto 0);
			ctrlind_20_ip_reset : in std_logic_vector(0 downto 0);
			Clk40MhzDerived5x2B00MHz : in std_logic;
			Clk40MhzDerived168x43B56_28MHz : in std_logic;
			tDiagramEnableOut : in std_logic
		);
	end component;

begin
	MyLabVIEWIP : NiFpgaAG_poc_ip_kria
		port map(
			reset => reset,
			enable_in => enable_in,
			enable_out => enable_out,
			enable_clr => enable_clr,
			ctrlind_00_DEBUG_TREADY => ctrlind_00_DEBUG_TREADY,
			ctrlind_01_DEBUG_TVALID => ctrlind_01_DEBUG_TVALID,
			ctrlind_02_DEBUG_TLAST => ctrlind_02_DEBUG_TLAST,
			ctrlind_03_DEBUG_TKEEP => ctrlind_03_DEBUG_TKEEP,
			ctrlind_04_DEBUG_TDATA => ctrlind_04_DEBUG_TDATA,
			ctrlind_05_CMD_TREADY => ctrlind_05_CMD_TREADY,
			ctrlind_06_CMD_TVALID => ctrlind_06_CMD_TVALID,
			ctrlind_07_CMD_TLAST => ctrlind_07_CMD_TLAST,
			ctrlind_08_CMD_TKEEP => ctrlind_08_CMD_TKEEP,
			ctrlind_09_CMD_TDATA => ctrlind_09_CMD_TDATA,
			ctrlind_10_MDEBUG_TREADY => ctrlind_10_MDEBUG_TREADY,
			ctrlind_11_MDEBUG_TVALID => ctrlind_11_MDEBUG_TVALID,
			ctrlind_12_MDEBUG_TLAST => ctrlind_12_MDEBUG_TLAST,
			ctrlind_13_MDEBUG_TKEEP => ctrlind_13_MDEBUG_TKEEP,
			ctrlind_14_MDEBUG_TDATA => ctrlind_14_MDEBUG_TDATA,
			ctrlind_15_TUSER => ctrlind_15_TUSER,
			ctrlind_16_TLAST => ctrlind_16_TLAST,
			ctrlind_17_TVALID => ctrlind_17_TVALID,
			ctrlind_18_TKEEP => ctrlind_18_TKEEP,
			ctrlind_19_TDATA => ctrlind_19_TDATA,
			ctrlind_20_ip_reset => ctrlind_20_ip_reset,
			Clk40MhzDerived5x2B00MHz => Clk40MhzDerived5x2B00MHz,
			Clk40MhzDerived168x43B56_28MHz => Clk40MhzDerived168x43B56_28MHz,
			tDiagramEnableOut => '1'
		);

end vhdl_labview;

