-- VHDL wrapper for NiFpgaAG_top_level
-- Generated by LabVIEW FPGA IP Export Utility
--
-- Ports:
-- reset      :  Reset port. Minimum assertion length: 8 base clock cycles.
--               Minimum de-assertion length: 40 base clock cycles.
-- enable_in  :  Enable in port. Minimum re-initialization length: 7 base clock cycles.
-- enable_out :  Enable out port.
-- enable_clr :  Enable clear port.
-- ctrlind_00_MAC_in : Top level control "MAC.in", unconnected in VI block diagram
-- ctrlind_01_fifo_2_tdata : Top level indicator "fifo_2.tdata", unconnected in VI block diagram
-- ctrlind_02_fifo_2_tready : Top level control "fifo_2.tready", sync to Clk40, bool
-- ctrlind_03_Add : Top level control "Add", unconnected in VI block diagram
-- ctrlind_04_fifo_1_tvalid : Top level control "fifo_1.tvalid", sync to Clk40, bool
-- ctrlind_05_fifo_1_tdata : Top level control "fifo_1.tdata", sync to Clk40, u64
-- ctrlind_06_B : Top level control "B", sync to Clk40, fxp(<+,4,4> [0,15]:1)
-- ctrlind_07_A : Top level control "A", sync to Clk40, fxp(<+,4,4> [0,15]:1)
-- ctrlind_08_Sum : Top level indicator "Sum", sync to Clk40, fxp(<+,5,5> [0,30]:1)
-- ctrlind_09_fifo_2_tvalid : Top level indicator "fifo_2.tvalid", sync to Clk40, bool
-- ctrlind_10_fifo_1_tready : Top level indicator "fifo_1.tready", sync to Clk40, bool
-- Clk40 : Clock "40 MHz Onboard Clock", nominal frequency 40.00 MHz, base clock

library ieee;
use ieee.std_logic_1164.all;

entity NiFpgaIPWrapper_top_level is
		port (
			reset : in std_logic;
			enable_in : in std_logic;
			enable_out : out std_logic;
			enable_clr : in std_logic;
			ctrlind_00_MAC_in : in std_logic_vector(47 downto 0);
			ctrlind_01_fifo_2_tdata : out std_logic_vector(63 downto 0);
			ctrlind_02_fifo_2_tready : in std_logic_vector(0 downto 0);
			ctrlind_03_Add : in std_logic_vector(3 downto 0);
			ctrlind_04_fifo_1_tvalid : in std_logic_vector(0 downto 0);
			ctrlind_05_fifo_1_tdata : in std_logic_vector(63 downto 0);
			ctrlind_06_B : in std_logic_vector(3 downto 0);
			ctrlind_07_A : in std_logic_vector(3 downto 0);
			ctrlind_08_Sum : out std_logic_vector(4 downto 0);
			ctrlind_09_fifo_2_tvalid : out std_logic_vector(0 downto 0);
			ctrlind_10_fifo_1_tready : out std_logic_vector(0 downto 0);
			Clk40 : in std_logic
		);
end NiFpgaIPWrapper_top_level;

architecture vhdl_labview of NiFpgaIPWrapper_top_level is

	component NiFpgaAG_top_level
		port (
			reset : in std_logic;
			enable_in : in std_logic;
			enable_out : out std_logic;
			enable_clr : in std_logic;
			ctrlind_00_MAC_in : in std_logic_vector(47 downto 0);
			ctrlind_01_fifo_2_tdata : out std_logic_vector(63 downto 0);
			ctrlind_02_fifo_2_tready : in std_logic_vector(0 downto 0);
			ctrlind_03_Add : in std_logic_vector(3 downto 0);
			ctrlind_04_fifo_1_tvalid : in std_logic_vector(0 downto 0);
			ctrlind_05_fifo_1_tdata : in std_logic_vector(63 downto 0);
			ctrlind_06_B : in std_logic_vector(3 downto 0);
			ctrlind_07_A : in std_logic_vector(3 downto 0);
			ctrlind_08_Sum : out std_logic_vector(4 downto 0);
			ctrlind_09_fifo_2_tvalid : out std_logic_vector(0 downto 0);
			ctrlind_10_fifo_1_tready : out std_logic_vector(0 downto 0);
			Clk40 : in std_logic;
			tDiagramEnableOut : in std_logic
		);
	end component;

begin
	MyLabVIEWIP : NiFpgaAG_top_level
		port map(
			reset => reset,
			enable_in => enable_in,
			enable_out => enable_out,
			enable_clr => enable_clr,
			ctrlind_00_MAC_in => ctrlind_00_MAC_in,
			ctrlind_01_fifo_2_tdata => ctrlind_01_fifo_2_tdata,
			ctrlind_02_fifo_2_tready => ctrlind_02_fifo_2_tready,
			ctrlind_03_Add => ctrlind_03_Add,
			ctrlind_04_fifo_1_tvalid => ctrlind_04_fifo_1_tvalid,
			ctrlind_05_fifo_1_tdata => ctrlind_05_fifo_1_tdata,
			ctrlind_06_B => ctrlind_06_B,
			ctrlind_07_A => ctrlind_07_A,
			ctrlind_08_Sum => ctrlind_08_Sum,
			ctrlind_09_fifo_2_tvalid => ctrlind_09_fifo_2_tvalid,
			ctrlind_10_fifo_1_tready => ctrlind_10_fifo_1_tready,
			Clk40 => Clk40,
			tDiagramEnableOut => '1'
		);

end vhdl_labview;

