-- VHDL wrapper for NiFpgaAG_fpga_sandbox
-- Generated by LabVIEW FPGA IP Export Utility
--
-- Ports:
-- reset      :  Reset port. Minimum assertion length: 3 base clock cycles.
--               Minimum de-assertion length: 40 base clock cycles.
-- enable_in  :  Enable in port. Minimum re-initialization length: 7 base clock cycles.
-- enable_out :  Enable out port.
-- enable_clr :  Enable clear port.
-- ctrlind_00_TDATA : Top level control "TDATA", sync to Clk40Derived168x43B56_25MHz, u64
-- ctrlind_01_O_TREADY : Top level control "O.TREADY", sync to Clk40Derived168x43B56_25MHz, bool
-- ctrlind_02_TVALID : Top level control "TVALID", sync to Clk40Derived168x43B56_25MHz, bool
-- ctrlind_03_NumB : Top level control "NumB", sync to Clk40Derived168x43B56_25MHz, i16
-- ctrlind_04_NumA : Top level control "NumA", sync to Clk40Derived168x43B56_25MHz, i16
-- ctrlind_05_SumOut : Top level indicator "SumOut", sync to Clk40Derived168x43B56_25MHz, i16
-- ctrlind_06_O_TVALID : Top level indicator "O.TVALID", sync to Clk40Derived168x43B56_25MHz, bool
-- ctrlind_07_O_TDATA : Top level indicator "O.TDATA", sync to Clk40Derived168x43B56_25MHz, u64
-- Clk40 : Clock "40 MHz Onboard Clock", nominal frequency 40.00 MHz, base clock
-- Clk40Derived168x43B56_25MHz : Clock "156.25MHz", nominal frequency 156.28 MHz

library ieee;
use ieee.std_logic_1164.all;

entity NiFpgaIPWrapper_fpga_sandbox is
		port (
			reset : in std_logic;
			enable_in : in std_logic;
			enable_out : out std_logic;
			enable_clr : in std_logic;
			ctrlind_00_TDATA : in std_logic_vector(63 downto 0);
			ctrlind_01_O_TREADY : in std_logic_vector(0 downto 0);
			ctrlind_02_TVALID : in std_logic_vector(0 downto 0);
			ctrlind_03_NumB : in std_logic_vector(15 downto 0);
			ctrlind_04_NumA : in std_logic_vector(15 downto 0);
			ctrlind_05_SumOut : out std_logic_vector(15 downto 0);
			ctrlind_06_O_TVALID : out std_logic_vector(0 downto 0);
			ctrlind_07_O_TDATA : out std_logic_vector(63 downto 0);
			Clk40 : in std_logic;
			Clk40Derived168x43B56_25MHz : in std_logic
		);
end NiFpgaIPWrapper_fpga_sandbox;

architecture vhdl_labview of NiFpgaIPWrapper_fpga_sandbox is

	component NiFpgaAG_fpga_sandbox
		port (
			reset : in std_logic;
			enable_in : in std_logic;
			enable_out : out std_logic;
			enable_clr : in std_logic;
			ctrlind_00_TDATA : in std_logic_vector(63 downto 0);
			ctrlind_01_O_TREADY : in std_logic_vector(0 downto 0);
			ctrlind_02_TVALID : in std_logic_vector(0 downto 0);
			ctrlind_03_NumB : in std_logic_vector(15 downto 0);
			ctrlind_04_NumA : in std_logic_vector(15 downto 0);
			ctrlind_05_SumOut : out std_logic_vector(15 downto 0);
			ctrlind_06_O_TVALID : out std_logic_vector(0 downto 0);
			ctrlind_07_O_TDATA : out std_logic_vector(63 downto 0);
			Clk40 : in std_logic;
			Clk40Derived168x43B56_25MHz : in std_logic;
			tDiagramEnableOut : in std_logic
		);
	end component;

begin
	MyLabVIEWIP : NiFpgaAG_fpga_sandbox
		port map(
			reset => reset,
			enable_in => enable_in,
			enable_out => enable_out,
			enable_clr => enable_clr,
			ctrlind_00_TDATA => ctrlind_00_TDATA,
			ctrlind_01_O_TREADY => ctrlind_01_O_TREADY,
			ctrlind_02_TVALID => ctrlind_02_TVALID,
			ctrlind_03_NumB => ctrlind_03_NumB,
			ctrlind_04_NumA => ctrlind_04_NumA,
			ctrlind_05_SumOut => ctrlind_05_SumOut,
			ctrlind_06_O_TVALID => ctrlind_06_O_TVALID,
			ctrlind_07_O_TDATA => ctrlind_07_O_TDATA,
			Clk40 => Clk40,
			Clk40Derived168x43B56_25MHz => Clk40Derived168x43B56_25MHz,
			tDiagramEnableOut => '1'
		);

end vhdl_labview;

