-- VHDL wrapper for NiFpgaAG_fpga_sandbox_ip
-- Generated by LabVIEW FPGA IP Export Utility
--
-- Ports:
-- reset      :  Reset port. Minimum assertion length: 8 base clock cycles.
--               Minimum de-assertion length: 100 base clock cycles.
-- enable_in  :  Enable in port. Minimum re-initialization length: 7 base clock cycles.
-- enable_out :  Enable out port.
-- enable_clr :  Enable clear port.
-- ctrlind_00_DEBUG_TVALID : Top level indicator "DEBUG.TVALID", sync to Clk40MhzDerived5x2B00MHz, bool
-- ctrlind_01_DEBUG_TLAST : Top level indicator "DEBUG.TLAST", sync to Clk40MhzDerived5x2B00MHz, bool
-- ctrlind_02_DEBUG_TKEEP : Top level indicator "DEBUG.TKEEP", sync to Clk40MhzDerived5x2B00MHz, u8
-- ctrlind_03_DEBUG_TDATA : Top level indicator "DEBUG.TDATA", sync to Clk40MhzDerived5x2B00MHz, u64
-- ctrlind_04_TREADY : Top level indicator "TREADY", sync to Clk40MhzDerived5x2B00MHz, bool
-- ctrlind_05_DEBUG_TREADY : Top level control "DEBUG.TREADY", unconnected in VI block diagram
-- ctrlind_06_B_in : Top level control "B.in", sync to Clk40MhzDerived5x2B00MHz, u8
-- ctrlind_07_A_in : Top level control "A.in", sync to Clk40MhzDerived5x2B00MHz, u8
-- ctrlind_08_Sum_Out : Top level indicator "Sum.Out", sync to Clk40MhzDerived5x2B00MHz, u8
-- ctrlind_09_TUSER : Top level control "TUSER", sync to Clk40MhzDerived5x2B00MHz, bool
-- ctrlind_10_TLAST : Top level control "TLAST", sync to Clk40MhzDerived5x2B00MHz, bool
-- ctrlind_11_TVALID : Top level control "TVALID", sync to Clk40MhzDerived5x2B00MHz, bool
-- ctrlind_12_TKEEP : Top level control "TKEEP", sync to Clk40MhzDerived5x2B00MHz, u8
-- ctrlind_13_TDATA : Top level control "TDATA", sync to Clk40MhzDerived5x2B00MHz, u64
-- ctrlind_14_ip_reset : Top level control "ip.reset", sync to Clk40MhzDerived5x2B00MHz, bool
-- Clk40MhzDerived5x2B00MHz : Clock "100MHz", nominal frequency 100.00 MHz, base clock

library ieee;
use ieee.std_logic_1164.all;

entity NiFpgaIPWrapper_fpga_sandbox_ip is
		port (
			reset : in std_logic;
			enable_in : in std_logic;
			enable_out : out std_logic;
			enable_clr : in std_logic;
			ctrlind_00_DEBUG_TVALID : out std_logic_vector(0 downto 0);
			ctrlind_01_DEBUG_TLAST : out std_logic_vector(0 downto 0);
			ctrlind_02_DEBUG_TKEEP : out std_logic_vector(7 downto 0);
			ctrlind_03_DEBUG_TDATA : out std_logic_vector(63 downto 0);
			ctrlind_04_TREADY : out std_logic_vector(0 downto 0);
			ctrlind_05_DEBUG_TREADY : in std_logic_vector(0 downto 0);
			ctrlind_06_B_in : in std_logic_vector(7 downto 0);
			ctrlind_07_A_in : in std_logic_vector(7 downto 0);
			ctrlind_08_Sum_Out : out std_logic_vector(7 downto 0);
			ctrlind_09_TUSER : in std_logic_vector(0 downto 0);
			ctrlind_10_TLAST : in std_logic_vector(0 downto 0);
			ctrlind_11_TVALID : in std_logic_vector(0 downto 0);
			ctrlind_12_TKEEP : in std_logic_vector(7 downto 0);
			ctrlind_13_TDATA : in std_logic_vector(63 downto 0);
			ctrlind_14_ip_reset : in std_logic_vector(0 downto 0);
			Clk40MhzDerived5x2B00MHz : in std_logic
		);
end NiFpgaIPWrapper_fpga_sandbox_ip;

architecture vhdl_labview of NiFpgaIPWrapper_fpga_sandbox_ip is

	component NiFpgaAG_fpga_sandbox_ip
		port (
			reset : in std_logic;
			enable_in : in std_logic;
			enable_out : out std_logic;
			enable_clr : in std_logic;
			ctrlind_00_DEBUG_TVALID : out std_logic_vector(0 downto 0);
			ctrlind_01_DEBUG_TLAST : out std_logic_vector(0 downto 0);
			ctrlind_02_DEBUG_TKEEP : out std_logic_vector(7 downto 0);
			ctrlind_03_DEBUG_TDATA : out std_logic_vector(63 downto 0);
			ctrlind_04_TREADY : out std_logic_vector(0 downto 0);
			ctrlind_05_DEBUG_TREADY : in std_logic_vector(0 downto 0);
			ctrlind_06_B_in : in std_logic_vector(7 downto 0);
			ctrlind_07_A_in : in std_logic_vector(7 downto 0);
			ctrlind_08_Sum_Out : out std_logic_vector(7 downto 0);
			ctrlind_09_TUSER : in std_logic_vector(0 downto 0);
			ctrlind_10_TLAST : in std_logic_vector(0 downto 0);
			ctrlind_11_TVALID : in std_logic_vector(0 downto 0);
			ctrlind_12_TKEEP : in std_logic_vector(7 downto 0);
			ctrlind_13_TDATA : in std_logic_vector(63 downto 0);
			ctrlind_14_ip_reset : in std_logic_vector(0 downto 0);
			Clk40MhzDerived5x2B00MHz : in std_logic;
			tDiagramEnableOut : in std_logic
		);
	end component;

begin
	MyLabVIEWIP : NiFpgaAG_fpga_sandbox_ip
		port map(
			reset => reset,
			enable_in => enable_in,
			enable_out => enable_out,
			enable_clr => enable_clr,
			ctrlind_00_DEBUG_TVALID => ctrlind_00_DEBUG_TVALID,
			ctrlind_01_DEBUG_TLAST => ctrlind_01_DEBUG_TLAST,
			ctrlind_02_DEBUG_TKEEP => ctrlind_02_DEBUG_TKEEP,
			ctrlind_03_DEBUG_TDATA => ctrlind_03_DEBUG_TDATA,
			ctrlind_04_TREADY => ctrlind_04_TREADY,
			ctrlind_05_DEBUG_TREADY => ctrlind_05_DEBUG_TREADY,
			ctrlind_06_B_in => ctrlind_06_B_in,
			ctrlind_07_A_in => ctrlind_07_A_in,
			ctrlind_08_Sum_Out => ctrlind_08_Sum_Out,
			ctrlind_09_TUSER => ctrlind_09_TUSER,
			ctrlind_10_TLAST => ctrlind_10_TLAST,
			ctrlind_11_TVALID => ctrlind_11_TVALID,
			ctrlind_12_TKEEP => ctrlind_12_TKEEP,
			ctrlind_13_TDATA => ctrlind_13_TDATA,
			ctrlind_14_ip_reset => ctrlind_14_ip_reset,
			Clk40MhzDerived5x2B00MHz => Clk40MhzDerived5x2B00MHz,
			tDiagramEnableOut => '1'
		);

end vhdl_labview;

